### PR TITLE
rbac: manifests: prune roles

### PR DESCRIPTION
**Pull request by fromanirh**
per https://kubernetes.io/docs/reference/access-authn-authz/rbac/:

"""
In the RBAC API, a role contains rules that represent a set of permissions.
Permissions are purely additive (there are no “deny” rules).
A role can be defined within a namespace with a Role, or cluster-wide with
a ClusterRole.
[...]
A ClusterRole can be used to grant the same permissions as a Role,
but because they are cluster-scoped, they can also be used to grant
access to:

- cluster-scoped resources (like nodes)
- non-resource endpoints (like “/healthz”)
- namespaced resources (like pods) across all namespaces (needed
  to run kubectl get pods --all-namespaces, for example)
"""

So we actually need only ClusterRoles, and their binding.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by MarSik** [comment]
Lgtm, but please make sure it works. This was the trickiest part of the whole operator stuff.

**Comment by fromanirh** [comment]
> Lgtm, but please make sure it works. This was the trickiest part of the whole operator stuff.

Sure, will test and report. Please not merge until then.

**Comment by fromanirh** [comment]
the template-validator, which was the component pulling these deps, deployed fine with this patch applied. However, I found https://github.com/operator-framework/operator-sdk/issues/1380 - which I think is unrelated. I think we can merge this patch after rebase

**Comment by fromanirh** [comment]
verified with https://github.com/MarSik/kubevirt-ssp-operator/pull/44

**Pull request merged**
